// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace _2026_RoomHub_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209172026_SeedRoomData")]
    partial class SeedRoomData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BorrowerId")
                        .HasColumnType("text");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 40,
                            Location = "Gedung A Lantai 1",
                            RoomCode = "LK-101",
                            RoomName = "Lab Komputer 1"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            Location = "Gedung A Lantai 1",
                            RoomCode = "LK-102",
                            RoomName = "Lab Komputer 2"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 35,
                            Location = "Gedung A Lantai 2",
                            RoomCode = "LK-201",
                            RoomName = "Lab Komputer 3"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 50,
                            Location = "Gedung B Lantai 1",
                            RoomCode = "RK-101",
                            RoomName = "Ruang Kelas 101"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 50,
                            Location = "Gedung B Lantai 1",
                            RoomCode = "RK-102",
                            RoomName = "Ruang Kelas 102"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 45,
                            Location = "Gedung B Lantai 1",
                            RoomCode = "RK-103",
                            RoomName = "Ruang Kelas 103"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 50,
                            Location = "Gedung B Lantai 2",
                            RoomCode = "RK-201",
                            RoomName = "Ruang Kelas 201"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 50,
                            Location = "Gedung B Lantai 2",
                            RoomCode = "RK-202",
                            RoomName = "Ruang Kelas 202"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 45,
                            Location = "Gedung B Lantai 2",
                            RoomCode = "RK-203",
                            RoomName = "Ruang Kelas 203"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 40,
                            Location = "Gedung B Lantai 3",
                            RoomCode = "RK-301",
                            RoomName = "Ruang Kelas 301"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 20,
                            Location = "Gedung C Lantai 1",
                            RoomCode = "RM-101",
                            RoomName = "Ruang Meeting 1"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 15,
                            Location = "Gedung C Lantai 1",
                            RoomCode = "RM-102",
                            RoomName = "Ruang Meeting 2"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 25,
                            Location = "Gedung C Lantai 2",
                            RoomCode = "RM-201",
                            RoomName = "Ruang Meeting 3"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 300,
                            Location = "Gedung D",
                            RoomCode = "AUD-01",
                            RoomName = "Auditorium Utama"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 150,
                            Location = "Gedung D",
                            RoomCode = "AUD-02",
                            RoomName = "Auditorium Mini"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 30,
                            Location = "Gedung E Lantai 1",
                            RoomCode = "LB-101",
                            RoomName = "Lab Bahasa"
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 30,
                            Location = "Gedung F Lantai 1",
                            RoomCode = "LF-101",
                            RoomName = "Lab Fisika 1"
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 30,
                            Location = "Gedung F Lantai 1",
                            RoomCode = "LF-102",
                            RoomName = "Lab Fisika 2"
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 25,
                            Location = "Gedung F Lantai 2",
                            RoomCode = "LK-103",
                            RoomName = "Lab Kimia"
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 20,
                            Location = "Gedung G Lantai 1",
                            RoomCode = "ST-101",
                            RoomName = "Studio Multimedia"
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 15,
                            Location = "Gedung G Lantai 1",
                            RoomCode = "ST-102",
                            RoomName = "Studio Recording"
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 48,
                            Location = "Gedung B Lantai 1",
                            RoomCode = "RK-104",
                            RoomName = "Ruang Kelas 104"
                        },
                        new
                        {
                            Id = 23,
                            Capacity = 48,
                            Location = "Gedung B Lantai 2",
                            RoomCode = "RK-204",
                            RoomName = "Ruang Kelas 204"
                        },
                        new
                        {
                            Id = 24,
                            Capacity = 40,
                            Location = "Gedung B Lantai 3",
                            RoomCode = "RK-302",
                            RoomName = "Ruang Kelas 302"
                        },
                        new
                        {
                            Id = 25,
                            Capacity = 35,
                            Location = "Gedung A Lantai 2",
                            RoomCode = "LP-101",
                            RoomName = "Lab Pemrograman"
                        },
                        new
                        {
                            Id = 26,
                            Capacity = 30,
                            Location = "Gedung A Lantai 3",
                            RoomCode = "LJ-101",
                            RoomName = "Lab Jaringan"
                        },
                        new
                        {
                            Id = 27,
                            Capacity = 100,
                            Location = "Gedung H Lantai 1",
                            RoomCode = "RS-101",
                            RoomName = "Ruang Seminar 1"
                        },
                        new
                        {
                            Id = 28,
                            Capacity = 80,
                            Location = "Gedung H Lantai 2",
                            RoomCode = "RS-102",
                            RoomName = "Ruang Seminar 2"
                        },
                        new
                        {
                            Id = 29,
                            Capacity = 12,
                            Location = "Gedung C Lantai 2",
                            RoomCode = "RM-103",
                            RoomName = "Ruang Meeting 4"
                        },
                        new
                        {
                            Id = 30,
                            Capacity = 25,
                            Location = "Gedung G Lantai 2",
                            RoomCode = "LD-101",
                            RoomName = "Lab Desain Grafis"
                        });
                });

            modelBuilder.Entity("Backend.Models.Booking", b =>
                {
                    b.HasOne("Backend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
